In [7]:
!pip3 install torch

In [65]:
import torch
from torch import tensor
import numpy as np

In [13]:
a = torch.ones((10, 10))
b = torch.tensor(11)
print(b.shape)
print(a.shape)

torch.Size([])
torch.Size([10, 10])


In [25]:
a[1, 1].dtype
b.dtype

torch.float32

In [26]:
points = torch.zeros(3, 4)

In [30]:
points[0, 1] = 10

In [38]:
c = torch.tensor([
    [1.0, 2.0],
    [3.0, 4.0]
])
print(c.dtype)
print(c.shape)

torch.float32
torch.Size([2, 2])


In [40]:
a = tensor([[1, 2], [3, 4]])

In [41]:
b = tensor([5, 6])

In [42]:
a * b

tensor([[ 5, 12],
        [15, 24]])

In [43]:
print(a.shape)
print(b.shape)

torch.Size([2, 2])
torch.Size([2])


In [44]:
c = torch.zeros((2, 1))

In [45]:
c

tensor([[0.],
        [0.]])

In [47]:
print(b)

tensor([5, 6])


In [50]:
print(a)

tensor([[1, 2],
        [3, 4]])


In [51]:
torch.dot(b, a)

RuntimeError: 1D tensors expected, got 1D, 2D tensors at /tmp/pip-req-build-as628lz5/aten/src/TH/generic/THTensorEvenMoreMath.cpp:83

In [55]:
b = b.reshape((1, 2))

In [56]:
torch.dot(b, a)

RuntimeError: 1D tensors expected, got 2D, 2D tensors at /tmp/pip-req-build-as628lz5/aten/src/TH/generic/THTensorEvenMoreMath.cpp:83

In [57]:
a.shape

torch.Size([2, 2])

In [58]:
b.shape

torch.Size([1, 2])

In [64]:
a

tensor([[1, 2],
        [3, 4]])

In [67]:
a = np.array([[1, 2], [3, 4]])
b = tensor(a)

In [76]:
b[0:1, :] = tensor([11, 12])

In [77]:
b

tensor([[11, 12],
        [ 3,  4]])

In [75]:
b[0:1, :] 

tensor([[1, 2]])

In [78]:
b.dtype

torch.int64

In [79]:
b.to(torch.float32)

tensor([[11., 12.],
        [ 3.,  4.]])

In [80]:
b

tensor([[11, 12],
        [ 3,  4]])

In [81]:
a = b.shape

In [96]:
torch.mean(b.float(), 1)

tensor([11.5000,  3.5000])

In [103]:
tensor([1, 2]) * 3

tensor([3, 6])

In [104]:
np.array([1, 2]) * 3

array([3, 6])

In [121]:
a = tensor([1, 2])
a = a.reshape((1, 2))
a = a.T
print(a.shape)
print(a)

torch.Size([2, 1])
tensor([[1],
        [2]])


In [128]:
a = a.repeat_interleave(3, dim=1)

In [133]:
a2 = a.to(torch.float32)
print(a2)
print(a2.exp())

tensor([[1., 1., 1.],
        [2., 2., 2.]])
tensor([[2.7183, 2.7183, 2.7183],
        [7.3891, 7.3891, 7.3891]])


In [134]:
a2.square()

tensor([[1., 1., 1.],
        [4., 4., 4.]])

In [135]:
a = tensor([[0, 1], [1, 0]])
b = tensor([[1, 2], [3, 4]])

In [136]:
a * b

tensor([[0, 2],
        [3, 0]])

In [138]:
a

tensor([[0, 1],
        [1, 0]])

In [139]:
b

tensor([[1, 2],
        [3, 4]])

In [146]:
tensor(1.23).item()

1.2300000190734863

In [150]:
b = tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

In [154]:
rp = torch.randperm(4)

In [157]:
b[:, rp]

tensor([[2, 4, 3, 1],
        [6, 8, 7, 5]])